repository: clintjedwards/mdserver
commands:
  build:
    - go mod tidy
    - go generate
    - go build -ldflags '-X "github.com/clintjedwards/{{.ProjectName}}/cli.appVersion={{.VersionFull}}"' -o {{.Path}}
